name: 检查更新

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */2 * * ?"

jobs:
  check:
#    name: check update
#    runs-on: windows-latest
    name: ♻ Update manifests
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@master
#    - name: scoop检查更新
#      shell: pwsh
#      run: |
#        set-executionpolicy remotesigned -scope currentuser
#        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
#        .\bin\checkver.ps1 -u
    - name: ⬇ Checkout repo
      uses: actions/checkout@master
    - name: ♻ Run autoupdate
      uses: foosel/scoop-checkver-action@main
      with:
        bucket: bucket
        force: ${{ github.event.inputs.force }}
    - name: 提交
      if: success()
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        $n = (git status -s | Measure-Object -Line)
        if($n.Lines -gt 0){ git commit -m "日常更新" -a}
    - run: git push
